#### ---------------------- HAFED config parameters -----------------

# Training hyper parameters
train_epoch: 50           # number of epochs
B: 1                      # batch size
warmup_epoch: 0           # number of warm-up epochs
wd: 0.00001               # weight decay
lr: 0.0001
min_lr: 0


# ACMIL model hyper parameters
n_token: 5    #number of models
n_masked_patch: 20    #top-K instances are be randomly masked


# HAFED model hyper parameters
n_token_1: 1    #number of models for attention block 1
n_token_2: 5    # number of models for attention block 2
n_masked_patch_1: 10    #top-K instances are be randomly masked in STKIM
n_masked_patch_2: 20
mask_drop: 0.4

# Dataset
dataset: camelyon16
n_class: 2                            # number of classes
data_dir:                             # dir path where all the high resolution paths are stored, Nxkxd


## pretrained backbone
backbone: 'ViT-S/16'   #'ResNet_50' 'ViT-S/16'
pretrain: 'medical_ssl' #natural_supervised medical_ssl
D_feat: 384
D_inner: 128

# Other hyper-params
n_worker: 8                          # number of workers
pin_memory: False                    # use pin memory in dataloader
n_shot: -1

dim_reduction: False