train_epoch: 500           # number of epochs
B: 1                       # batch size
warmup_epoch: 0            # number of warm-up epochs
reg: 0.005                 # weight decay
lr: 0.0003
min_lr: 0

# Dataset details
frac: 0.2
cosine_threshold: 0.92
dataset: tcga
n_class: 2

ckpt_path:   # HAFED classifier checkpoint
level1_path: # Intermediate feature representation path from step4
level3_path: # Low resolution feature extraction from step2

# Other hyper-params
backbone: 'ViT-S/16'
pretrain: 'medical_ssl'
nhead: 2
nlayer: 1
ff_dim: 512
dropout: 0.2
pick_action_from_non_visited_patches: True
n_worker: 8                          # number of workers
pin_memory: False                    # use pin memory in dataloade
