## RL hyper parameters
B: 1

# Dataset details
dataset: tcga
fglobal: 'mlp'

## pretrained backbone
backbone: 'ViT-S/16'   #'ResNet_50' 'ViT-S/16'
pretrain: 'medical_ssl' #natural_supervised medical_ssl
D_feat: 384
D_inner: 128
only_ce_as_reward: True


# Model weights -
frac_visit: 0.2
cosine_threshold: 0.95
classifier_ckpt_path:         # HAFED classifier ckpt path
mlp_fglobal_ckpt :            # TSU model checkpoint path ---> Need to be same, as cosine threshold paramters is mentioned
level1_path:                  # HAFED intermediate feature representation path from step 4
level3_path:                  # Low resolution feature path from step 2
rl_ckpt_path:                 # Load the SASHA-RL Agent checkpoint .pt file

# Extra Hyper params
n_worker: 8
pin_memory: False
n_shot: -1
dim_reduction: False