#### ---------------------- HAFED config parameters -----------------
train_epoch: 50           # number of epochs
B: 1                 # batch size
warmup_epoch: 0    # number of warm-up epochs
wd: 0.0001             # weight decay
lr: 0.0004
min_lr: 0


# ACMIL model hyper parameters
n_token: 1    #number of models
n_masked_patch: 20    #top-K instances are be randomly masked

# HAFED model hyper parameters
n_token_1: 1    #number of models for attention block 1
n_token_2: 1    # number of models for attention block 2
n_masked_patch_1: 10    #top-K instances are be randomly masked in STKIM
n_masked_patch_2: 20
mask_drop: 0.4

# Dataset
dataset: tcga
n_class: 2                            # number of classes
data_dir:                             # directory of dataset
data_csv:                             # dataset csv file path in dataset_csv/tcga

## pretrained backbone
backbone: 'ViT-S/16'   #'ResNet_50' 'ViT-S/16'
pretrain: 'medical_ssl' #natural_supervised medical_ssl
D_feat: 384
D_inner: 128

# Other hyperparams
n_worker: 8                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1
dim_reduction: False
